//! 本地 WorkBuddy / CodeBuddy CLI JSONL Token 统计。
use serde_json::{json, Value};
use std::collections::HashMap;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};

#[derive(Clone, Copy, Debug, Default, PartialEq)]
struct Usage { input: u64, output: u64, read: u64, write: u64 }
#[derive(Clone, Debug, Default)] struct Totals { u: Usage, records: u64 }
impl Totals { fn add(&mut self,u:Usage){self.u.input+=u.input;self.u.output+=u.output;self.u.read+=u.read;self.u.write+=u.write;self.records+=1;} fn value(&self)->Value{json!({"input":self.u.input,"output":self.u.output,"cacheRead":self.u.read,"cacheWrite":self.u.write,"uncachedInput":self.u.input.saturating_sub(self.u.read),"records":self.records,"cacheHitRate":(self.u.input>0).then(||self.u.read as f64/self.u.input as f64)})} }
fn n(v:&Value,keys:&[&str])->Option<u64>{keys.iter().find_map(|k|v.get(*k)).and_then(|x|x.as_u64().or_else(||x.as_f64().map(|n|n.max(0.0)as u64)).or_else(||x.as_str()?.parse().ok()))}
fn usage(v:&Value)->Option<Usage>{let p=v.get("providerData");let sources=[v.get("message").and_then(|x|x.get("usage")),p.and_then(|x|x.get("usage")),v.get("usage"),p.and_then(|x|x.get("rawUsage"))];let input=sources.iter().flatten().find_map(|x|n(x,&["input_tokens","inputTokens","prompt_tokens"]))?;let output=sources.iter().flatten().find_map(|x|n(x,&["output_tokens","outputTokens","completion_tokens"])).unwrap_or(0);let read=sources.iter().flatten().find_map(|x|n(x,&["cache_read_input_tokens","cacheReadInputTokens","prompt_cache_hit_tokens","cached_tokens"])).unwrap_or(0);let write=sources.iter().flatten().find_map(|x|n(x,&["cache_write_input_tokens","cacheWriteInputTokens","cache_creation_input_tokens","prompt_cache_write_tokens"])).unwrap_or(0);Some(Usage{input,output,read,write})}
fn model(v:&Value)->String{v.get("providerData").and_then(|x|x.get("model")).or_else(||v.get("model")).and_then(Value::as_str).map(str::trim).filter(|x|!x.is_empty()).unwrap_or("未知模型").to_string()}
fn date(v:&Value)->Option<String>{let ts=v.get("timestamp").or_else(||v.get("ts")).and_then(Value::as_i64)?;chrono::DateTime::from_timestamp_millis(ts).map(|d|d.with_timezone(&chrono::Local).format("%Y-%m-%d").to_string())}
fn files(root:&Path,out:&mut Vec<PathBuf>){let Ok(es)=std::fs::read_dir(root)else{return};for e in es.flatten(){let p=e.path();if p.is_dir(){if p.file_name().and_then(|x|x.to_str())!=Some("subagents"){files(&p,out)}}else if p.extension().and_then(|x|x.to_str())==Some("jsonl"){out.push(p)}}}
fn groups(m:HashMap<String,Totals>)->Vec<Value>{m.into_iter().map(|(k,t)|{let mut v=t.value();v["key"]=json!(k);v}).collect()}
fn source(root:PathBuf,name:&str)->Value{let mut ps=Vec::new();files(&root,&mut ps);let(mut total,mut models,mut sessions,mut daily,mut errors)=(Totals::default(),HashMap::new(),HashMap::new(),HashMap::new(),0u64);for p in &ps{let sid=p.file_stem().and_then(|x|x.to_str()).unwrap_or("未知");let project=p.parent().and_then(Path::file_name).and_then(|x|x.to_str()).unwrap_or("未知");let Ok(f)=std::fs::File::open(p)else{errors+=1;continue};for line in BufReader::new(f).lines(){let Ok(line)=line else{errors+=1;continue};let Ok(v)=serde_json::from_str::<Value>(&line)else{errors+=1;continue};let Some(u)=usage(&v)else{continue};total.add(u);models.entry(model(&v)).or_insert_with(Totals::default).add(u);sessions.entry(format!("{project} · {sid}")).or_insert_with(Totals::default).add(u);if let Some(d)=date(&v){daily.entry(d).or_insert_with(Totals::default).add(u)}}}let daily=groups(daily);json!({"source":name,"root":root.to_string_lossy(),"summary":total.value(),"models":groups(models),"sessions":groups(sessions),"daily":daily,"filesScanned":ps.len(),"parseErrors":errors})}
pub fn get_statistics()->Value{let h=dirs::home_dir().unwrap_or_else(||PathBuf::from("."));json!({"generatedAt":crate::modules::config::now_ms(),"sources":[source(h.join(".workbuddy/projects"),"workbuddy"),source(h.join(".codebuddy/projects"),"codebuddy-cli")]})}
#[cfg(test)]mod tests{use super::*;#[test]fn usage_priority_and_aliases(){let v=json!({"providerData":{"usage":{"inputTokens":99,"outputTokens":22},"rawUsage":{"prompt_cache_write_tokens":2}},"message":{"usage":{"input_tokens":10,"output_tokens":3,"cache_read_input_tokens":4}}});assert_eq!(usage(&v),Some(Usage{input:10,output:3,read:4,write:2}));}}
